---
galaxy_info:
  author: Roman Kuzmitskii <ansible@damex.org>
  description: incus role
  license: GPLv2
  min_ansible_version: 2.19.0
  platforms:
    - name: Debian
      versions:
        - all
    - name: Fedora
      versions:
        - all
    - name: EL
      versions:
        - all
dependencies: []
