---
incus_package_name: incus
incus_package_state: present
incus_service_name: incus
incus_apt_key_id: C838DCFD
incus_apt_key_url: https://pkgs.zabbly.com/key.asc
incus_apt_repository_name: incus
incus_apt_repository_url: https://pkgs.zabbly.com/incus/stable
incus_apt_repository_components:
  - main
