---
- name: Ensure incus apt key {{ incus_apt_key_id }}
  ansible.builtin.include_role:
    name: damex.apt.apt_keys
  vars:
    apt_keys: # noqa: var-naming[no-role-prefix]
      - id: "{{ incus_apt_key_id }}"
        url: "{{ incus_apt_key_url }}"
  when: ansible_facts['pkg_mgr'] == "apt"
